//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class chem_databaseEntities2 : DbContext
{
    public chem_databaseEntities2()
        : base("name=chem_databaseEntities2")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<Class_Information> Class_Information { get; set; }
    public DbSet<Course_Information> Course_Information { get; set; }
    public DbSet<Equipment_Information> Equipment_Information { get; set; }
    public DbSet<login_information> login_information { get; set; }
    public DbSet<Login_News> Login_News { get; set; }
    public DbSet<login_rank> login_rank { get; set; }
    public DbSet<Class_Course> Class_Course { get; set; }
    public DbSet<Class_Exper> Class_Exper { get; set; }
    public DbSet<Course_Exper> Course_Exper { get; set; }
    public DbSet<Equipment_Loc> Equipment_Loc { get; set; }
    public DbSet<Room> Room { get; set; }
    public DbSet<Experment_Information> Experment_Information { get; set; }
    public DbSet<Experment_Room> Experment_Room { get; set; }
    public DbSet<Drug_Information> Drug_Information { get; set; }
    public DbSet<Drug_In_Out> Drug_In_Out { get; set; }
    public DbSet<Drug_Loc> Drug_Loc { get; set; }
    public DbSet<Course_Login> Course_Login { get; set; }
    public DbSet<Experment_Login> Experment_Login { get; set; }
    public DbSet<Drug_MixDrug> Drug_MixDrug { get; set; }
    public DbSet<Drug_Mix> Drug_Mix { get; set; }
    public DbSet<Experment_Drug> Experment_Drug { get; set; }
    public DbSet<Experment_MixDrug> Experment_MixDrug { get; set; }
    public DbSet<Student_Freetime> Student_Freetime { get; set; }
    public DbSet<Student_Signtime> Student_Signtime { get; set; }
    public DbSet<Student_Worktime> Student_Worktime { get; set; }
    public DbSet<ImageCheck> ImageCheck { get; set; }
}
