//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Class_Course
{
    public string class_name { get; set; }
    public string course { get; set; }
    public string people { get; set; }
}

public partial class Class_Exper
{
    public string class_name { get; set; }
    public string experment_name { get; set; }
    public string room_name { get; set; }
}

public partial class Class_Information
{
    public string class_name { get; set; }
    public string detail { get; set; }
    public Nullable<int> num { get; set; }
}

public partial class Course_Exper
{
    public string course { get; set; }
    public string experment_name { get; set; }

    public virtual Course_Information Course_Information { get; set; }
}

public partial class Course_Information
{
    public Course_Information()
    {
        this.Course_Exper = new HashSet<Course_Exper>();
        this.Course_Login = new HashSet<Course_Login>();
    }

    public string course { get; set; }
    public string detail { get; set; }
    public string faculty { get; set; }

    public virtual ICollection<Course_Exper> Course_Exper { get; set; }
    public virtual ICollection<Course_Login> Course_Login { get; set; }
}

public partial class Course_Login
{
    public string course { get; set; }
    public string ID { get; set; }
    public string name { get; set; }
    public string isAdd { get; set; }

    public virtual Course_Information Course_Information { get; set; }
    public virtual login_rank login_rank { get; set; }
}

public partial class Drug_In_Out
{
    public string drug_name { get; set; }
    public double change { get; set; }
    public string people { get; set; }
    public string standard { get; set; }
    public string type { get; set; }
    public System.DateTime time { get; set; }
    public string position { get; set; }

    public virtual Drug_Information Drug_Information { get; set; }
}

public partial class Drug_Information
{
    public Drug_Information()
    {
        this.Drug_In_Out = new HashSet<Drug_In_Out>();
        this.Drug_Loc = new HashSet<Drug_Loc>();
        this.Drug_MixDrug = new HashSet<Drug_MixDrug>();
        this.Experment_Drug = new HashSet<Experment_Drug>();
    }

    public string drug_name { get; set; }
    public string drug_another_name { get; set; }
    public string drug_Englishname { get; set; }
    public string fen_zi_shi { get; set; }
    public string fen_zi_liang { get; set; }
    public string CAS { get; set; }
    public string details { get; set; }
    public string dangerous { get; set; }
    public double counting { get; set; }
    public string standard { get; set; }
    public string people { get; set; }
    public System.DateTime edit_time { get; set; }

    public virtual ICollection<Drug_In_Out> Drug_In_Out { get; set; }
    public virtual ICollection<Drug_Loc> Drug_Loc { get; set; }
    public virtual ICollection<Drug_MixDrug> Drug_MixDrug { get; set; }
    public virtual ICollection<Experment_Drug> Experment_Drug { get; set; }
}

public partial class Drug_Loc
{
    public int id { get; set; }
    public string drug_name { get; set; }
    public string position { get; set; }
    public int counting { get; set; }
    public double remain { get; set; }
    public Nullable<double> each { get; set; }
    public string standard { get; set; }
    public string people { get; set; }
    public System.DateTime edit_time { get; set; }

    public virtual Drug_Information Drug_Information { get; set; }
}

public partial class Drug_Mix
{
    public Drug_Mix()
    {
        this.Drug_MixDrug = new HashSet<Drug_MixDrug>();
        this.Experment_MixDrug = new HashSet<Experment_MixDrug>();
    }

    public string drug_mix { get; set; }
    public string attention { get; set; }
    public string standard { get; set; }

    public virtual ICollection<Drug_MixDrug> Drug_MixDrug { get; set; }
    public virtual ICollection<Experment_MixDrug> Experment_MixDrug { get; set; }
}

public partial class Drug_MixDrug
{
    public string drug_mix { get; set; }
    public string drug_name { get; set; }
    public double num { get; set; }
    public string standard { get; set; }

    public virtual Drug_Information Drug_Information { get; set; }
    public virtual Drug_Mix Drug_Mix { get; set; }
}

public partial class Equipment_Information
{
    public Equipment_Information()
    {
        this.Equipment_Loc = new HashSet<Equipment_Loc>();
    }

    public string equip_name { get; set; }
    public string model { get; set; }
    public string factory { get; set; }
    public string detail { get; set; }
    public string price { get; set; }

    public virtual ICollection<Equipment_Loc> Equipment_Loc { get; set; }
}

public partial class Equipment_Loc
{
    public string equip_name { get; set; }
    public string fixed_assets_NO { get; set; }
    public string factory_NO { get; set; }
    public string time_buying { get; set; }
    public string people { get; set; }
    public string position { get; set; }
    public string state { get; set; }
    public string state_explane { get; set; }
    public Nullable<System.DateTime> edit_time { get; set; }

    public virtual Equipment_Information Equipment_Information { get; set; }
}

public partial class Experment_Drug
{
    public string experment_name { get; set; }
    public string drug_name { get; set; }
    public double num { get; set; }
    public string standard { get; set; }

    public virtual Drug_Information Drug_Information { get; set; }
    public virtual Experment_Information Experment_Information { get; set; }
}

public partial class Experment_Information
{
    public Experment_Information()
    {
        this.Experment_Room = new HashSet<Experment_Room>();
        this.Experment_Login = new HashSet<Experment_Login>();
        this.Experment_Drug = new HashSet<Experment_Drug>();
        this.Experment_MixDrug = new HashSet<Experment_MixDrug>();
    }

    public string experment_name { get; set; }
    public string detail { get; set; }
    public Nullable<double> error { get; set; }

    public virtual ICollection<Experment_Room> Experment_Room { get; set; }
    public virtual ICollection<Experment_Login> Experment_Login { get; set; }
    public virtual ICollection<Experment_Drug> Experment_Drug { get; set; }
    public virtual ICollection<Experment_MixDrug> Experment_MixDrug { get; set; }
}

public partial class Experment_Login
{
    public string experment_name { get; set; }
    public string ID { get; set; }
    public string name { get; set; }
    public string isAdd { get; set; }

    public virtual Experment_Information Experment_Information { get; set; }
    public virtual login_rank login_rank { get; set; }
}

public partial class Experment_MixDrug
{
    public string experment_name { get; set; }
    public string drug_mix { get; set; }
    public double num { get; set; }
    public string standard { get; set; }

    public virtual Drug_Mix Drug_Mix { get; set; }
    public virtual Experment_Information Experment_Information { get; set; }
}

public partial class Experment_Room
{
    public string experment_name { get; set; }
    public string room_name { get; set; }
    public string Detail { get; set; }

    public virtual Experment_Information Experment_Information { get; set; }
    public virtual Room Room { get; set; }
}

public partial class ImageCheck
{
    public int No { get; set; }
    public string str { get; set; }
    public Nullable<System.DateTime> date { get; set; }
}

public partial class login_information
{
    public string ID { get; set; }
    public string name { get; set; }
    public Nullable<System.DateTime> creat_time { get; set; }
    public string idebtity { get; set; }
    public string email { get; set; }
    public string QQ { get; set; }
    public string phonenumber_long { get; set; }
    public string phonenumber_short { get; set; }
    public string address { get; set; }
    public Nullable<System.DateTime> last_time { get; set; }

    public virtual login_rank login_rank { get; set; }
}

public partial class Login_News
{
    public int ArticleID { get; set; }
    public string Title { get; set; }
    public string Content_1 { get; set; }
    public Nullable<System.DateTime> DateTime { get; set; }
    public Nullable<int> Hits { get; set; }
    public string Member_Name { get; set; }
    public Nullable<int> type { get; set; }
    public string infor { get; set; }
}

public partial class login_rank
{
    public login_rank()
    {
        this.Course_Login = new HashSet<Course_Login>();
        this.Experment_Login = new HashSet<Experment_Login>();
        this.Student_Freetime = new HashSet<Student_Freetime>();
        this.Student_Signtime = new HashSet<Student_Signtime>();
        this.Student_Worktime = new HashSet<Student_Worktime>();
    }

    public string ID { get; set; }
    public string PW { get; set; }
    public string name { get; set; }
    public string question { get; set; }
    public string answer { get; set; }
    public string rank_control { get; set; }
    public string rank_news { get; set; }
    public string rank_drug { get; set; }
    public string rank_equipment { get; set; }
    public string rank_experment { get; set; }
    public string rank_course { get; set; }
    public string rank_class { get; set; }
    public string rank_student { get; set; }
    public string rank_open { get; set; }
    public string token { get; set; }
    public Nullable<System.DateTime> token_Time { get; set; }

    public virtual login_information login_information { get; set; }
    public virtual ICollection<Course_Login> Course_Login { get; set; }
    public virtual ICollection<Experment_Login> Experment_Login { get; set; }
    public virtual ICollection<Student_Freetime> Student_Freetime { get; set; }
    public virtual ICollection<Student_Signtime> Student_Signtime { get; set; }
    public virtual ICollection<Student_Worktime> Student_Worktime { get; set; }
}

public partial class Room
{
    public Room()
    {
        this.Experment_Room = new HashSet<Experment_Room>();
    }

    public string room_name { get; set; }
    public string detail { get; set; }

    public virtual ICollection<Experment_Room> Experment_Room { get; set; }
}

public partial class Student_Freetime
{
    public int freetime_id { get; set; }
    public string ID { get; set; }
    public string name { get; set; }
    public Nullable<int> time_type { get; set; }

    public virtual login_rank login_rank { get; set; }
}

public partial class Student_Signtime
{
    public int time_id { get; set; }
    public string ID { get; set; }
    public string name { get; set; }
    public Nullable<System.DateTime> date_time { get; set; }
    public string state { get; set; }

    public virtual login_rank login_rank { get; set; }
}

public partial class Student_Worktime
{
    public int time_id { get; set; }
    public string ID { get; set; }
    public string name { get; set; }
    public Nullable<int> time_type { get; set; }
    public Nullable<System.DateTime> date_time { get; set; }

    public virtual login_rank login_rank { get; set; }
}
